# Generated by Django 3.0 on 2020-10-10 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(blank=True, max_length=120, null=True)),
                ('CompanyName', models.CharField(blank=True, max_length=120, null=True)),
                ('ContactPerson', models.CharField(blank=True, max_length=120, null=True)),
                ('ContactPersonDesignation', models.CharField(blank=True, max_length=120, null=True)),
                ('Address', models.CharField(blank=True, max_length=120, null=True)),
                ('PurposeValuation', models.CharField(blank=True, max_length=120, null=True)),
                ('DateOfReport', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolatilityXcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComparableCompany', models.CharField(blank=True, max_length=50, null=True)),
                ('Ticker', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrbenapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='VolatilityAvgXcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparablecompanies', models.CharField(blank=True, max_length=50, null=True)),
                ('companyvolatilityAvg', models.FloatField(default=0.0)),
                ('period', models.FloatField(default=0.0)),
                ('TotalPeriodAvg', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrbenapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='VestingXcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vesting', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vesting')),
                ('VestingDate', models.DateField(blank=True, null=True, verbose_name='Vesting date')),
                ('NumOfEsop', models.IntegerField(default=0, verbose_name='Number of ESOP vested')),
                ('PerEsop', models.FloatField(default=0, verbose_name='Percentage of ESOP vested')),
                ('ExcerciseDate', models.DateField(blank=True, null=True, verbose_name='Exercise Date')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrbenapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='RiskFreeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.FloatField(default=0)),
                ('riskfreerate', models.FloatField(default=0)),
                ('VolatilityAverage', models.FloatField(default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrbenapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='RiskExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vesting', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.FloatField(default=0.0)),
                ('riskfree', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrbenapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('VestingDate', models.DateField(blank=True, null=True, verbose_name='Vesting date')),
                ('NumOfEsop', models.IntegerField(default=0, verbose_name='Number of ESOP vested')),
                ('PerEsop', models.FloatField(default=0, verbose_name='Percentage of ESOP vested')),
                ('GrantDate', models.DateField(blank=True, null=True)),
                ('VestingPeriod', models.FloatField(default=0.0)),
                ('FairValueofShare', models.FloatField(default=0.0)),
                ('ExcersisePrice', models.FloatField(default=0.0)),
                ('RiskFRate', models.FloatField(default=0.0)),
                ('Volatility', models.FloatField(default=0.0)),
                ('DividendPayout', models.FloatField(default=0.0)),
                ('FairValueofOption', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrbenapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='EsopDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grants', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('', '')], max_length=3, null=True)),
                ('GrantDate', models.DateField(blank=True, null=True)),
                ('ESOPGranted', models.IntegerField(default=0)),
                ('VestingOnMarket', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('', '')], max_length=3, null=True)),
                ('ValuationAvailable', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('', '')], max_length=3, null=True)),
                ('EquityValuePerShare', models.FloatField(default=0)),
                ('ExercisePrice', models.FloatField(default=0)),
                ('CountryOfIncorporation', models.CharField(blank=True, max_length=120, null=True)),
                ('DividendYield', models.FloatField(default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warrbenapp.Project')),
            ],
        ),
    ]
