# Generated by Django 3.0 on 2020-10-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrbenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestingxcel',
            name='NumOfEsop',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of ESOP vested'),
        ),
    ]
