# Generated by Django 3.0 on 2020-10-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warrbenapp', '0002_auto_20201011_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vestingxcel',
            name='PerEsop',
            field=models.FloatField(default=0, null=True, verbose_name='Percentage of ESOP vested'),
        ),
    ]
