# Generated by Django 3.0 on 2020-10-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warrbenapp', '0003_auto_20201011_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vestingxcel',
            name='PerEsop',
        ),
    ]
